export const URL = 'https://norma.nomoreparties.space/api';
export const wsUrl = 'wss://norma.nomoreparties.space/orders/all';

export const dataOrders = [
    {
        id: '111111',
        date: 'Сегодня, 16:20 i-GMT+3',
        name: 'Death Start Starship Main бургер',
        ingredients: [
            {
                "_id": "60d3b41abdacab0026a733c6",
                "name": "Краторная булка N-200i",
                "type": "bun",
                "proteins": 80,
                "fat": 24,
                "carbohydrates": 53,
                "calories": 420,
                "price": 1255,
                "image": "https://code.s3.yandex.net/react/code/bun-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
                "__v": 0,
                "uuid": "160d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c8",
                "name": "Филе Люминесцентного тетраодонтимформа",
                "type": "main",
                "proteins": 44,
                "fat": 26,
                "carbohydrates": 85,
                "calories": 643,
                "price": 988,
                "image": "https://code.s3.yandex.net/react/code/meat-03.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-03-large.png",
                "__v": 0,
                "uuid": "260d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "360d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733cc",
                "name": "Соус Spicy-X",
                "type": "sauce",
                "proteins": 30,
                "fat": 20,
                "carbohydrates": 40,
                "calories": 30,
                "price": 90,
                "image": "https://code.s3.yandex.net/react/code/sauce-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/sauce-02-large.png",
                "__v": 0,
                "uuid": "460d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733cd",
                "name": "Соус фирменный Space Sauce",
                "type": "sauce",
                "proteins": 50,
                "fat": 22,
                "carbohydrates": 11,
                "calories": 14,
                "price": 80,
                "image": "https://code.s3.yandex.net/react/code/sauce-04.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/sauce-04-large.png",
                "__v": 0,
                "uuid": "560d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733d0",
                "name": "Хрустящие минеральные кольца",
                "type": "main",
                "proteins": 808,
                "fat": 689,
                "carbohydrates": 609,
                "calories": 986,
                "price": 300,
                "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
                "__v": 0,
                "uuid": "660d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733d0",
                "name": "Хрустящие минеральные кольца",
                "type": "main",
                "proteins": 808,
                "fat": 689,
                "carbohydrates": 609,
                "calories": 986,
                "price": 300,
                "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
                "__v": 0,
                "uuid": "760d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "860d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "960d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "060d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "1160d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "1260d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c6",
                "name": "Краторная булка N-200i",
                "type": "bun",
                "proteins": 80,
                "fat": 24,
                "carbohydrates": 53,
                "calories": 420,
                "price": 1255,
                "image": "https://code.s3.yandex.net/react/code/bun-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
                "__v": 0,
                "uuid": "1360d3b41abdacab0026a733c6",
            }
        ],
        price: '666',
    },
    {
        id: '222222',
        date: 'Сегодня, 16:20 i-GMT+3',
        name: 'Interstellar бургер',
        ingredients: [
            {
                "_id": "60d3b41abdacab0026a733c7",
                "name": "Флюоресцентная булка R2-D3",
                "type": "bun",
                "proteins": 44,
                "fat": 26,
                "carbohydrates": 85,
                "calories": 643,
                "price": 988,
                "image": "https://code.s3.yandex.net/react/code/bun-01.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/bun-01-large.png",
                "__v": 0,
                "uuid": "1460d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c8",
                "name": "Филе Люминесцентного тетраодонтимформа",
                "type": "main",
                "proteins": 44,
                "fat": 26,
                "carbohydrates": 85,
                "calories": 643,
                "price": 988,
                "image": "https://code.s3.yandex.net/react/code/meat-03.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-03-large.png",
                "__v": 0,
                "uuid": "1560d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "1660d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "1760d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "1860d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "1960d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "1060d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c7",
                "name": "Флюоресцентная булка R2-D3",
                "type": "bun",
                "proteins": 44,
                "fat": 26,
                "carbohydrates": 85,
                "calories": 643,
                "price": 988,
                "image": "https://code.s3.yandex.net/react/code/bun-01.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/bun-01-large.png",
                "__v": 0,
                "uuid": "2160d3b41abdacab0026a733c6",
            }
        ],
        price: '1337',
    },
    {
        id: '333333',
        date: 'Сегодня, 16:20 i-GMT+3',
        name: 'Black Hole Singularity острый бургер',
        ingredients: [
            {
                "_id": "60d3b41abdacab0026a733c6",
                "name": "Краторная булка N-200i",
                "type": "bun",
                "proteins": 80,
                "fat": 24,
                "carbohydrates": 53,
                "calories": 420,
                "price": 1255,
                "image": "https://code.s3.yandex.net/react/code/bun-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
                "__v": 0,
                "uuid": "2260d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "2360d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c6",
                "name": "Краторная булка N-200i",
                "type": "bun",
                "proteins": 80,
                "fat": 24,
                "carbohydrates": 53,
                "calories": 420,
                "price": 1255,
                "image": "https://code.s3.yandex.net/react/code/bun-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
                "__v": 0,
                "uuid": "2460d3b41abdacab0026a733c6",
            }
        ],
        price: '228',
    },
    {
        id: '444444',
        date: 'Сегодня, 16:20 i-GMT+3',
        name: 'Supernova Infinity бургер',
        ingredients: [
            {
                "_id": "60d3b41abdacab0026a733c6",
                "name": "Краторная булка N-200i",
                "type": "bun",
                "proteins": 80,
                "fat": 24,
                "carbohydrates": 53,
                "calories": 420,
                "price": 1255,
                "image": "https://code.s3.yandex.net/react/code/bun-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
                "__v": 0,
                "uuid": "2560d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c8",
                "name": "Филе Люминесцентного тетраодонтимформа",
                "type": "main",
                "proteins": 44,
                "fat": 26,
                "carbohydrates": 85,
                "calories": 643,
                "price": 988,
                "image": "https://code.s3.yandex.net/react/code/meat-03.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-03-large.png",
                "__v": 0,
                "uuid": "2660d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "2760d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "2860d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "2960d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "3060d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "3160d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "3260d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c6",
                "name": "Краторная булка N-200i",
                "type": "bun",
                "proteins": 80,
                "fat": 24,
                "carbohydrates": 53,
                "calories": 420,
                "price": 1255,
                "image": "https://code.s3.yandex.net/react/code/bun-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
                "__v": 0,
                "uuid": "3360d3b41abdacab0026a733c6",
            }
        ],
        price: '42',
    },
    {
        id: '555555',
        date: 'Сегодня, 16:20 i-GMT+3',
        name: 'Death Start Starship Main бургер',
        ingredients: [
            {
                "_id": "60d3b41abdacab0026a733c6",
                "name": "Краторная булка N-200i",
                "type": "bun",
                "proteins": 80,
                "fat": 24,
                "carbohydrates": 53,
                "calories": 420,
                "price": 1255,
                "image": "https://code.s3.yandex.net/react/code/bun-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
                "__v": 0,
                "uuid": "3460d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c8",
                "name": "Филе Люминесцентного тетраодонтимформа",
                "type": "main",
                "proteins": 44,
                "fat": 26,
                "carbohydrates": 85,
                "calories": 643,
                "price": 988,
                "image": "https://code.s3.yandex.net/react/code/meat-03.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-03-large.png",
                "__v": 0,
                "uuid": "3560d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "3660d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "3760d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "3860d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "3960d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "4060d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "4160d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c6",
                "name": "Краторная булка N-200i",
                "type": "bun",
                "proteins": 80,
                "fat": 24,
                "carbohydrates": 53,
                "calories": 420,
                "price": 1255,
                "image": "https://code.s3.yandex.net/react/code/bun-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
                "__v": 0,
                "uuid": "4260d3b41abdacab0026a733c6",
            }
        ],
        price: '13',
    },
    {
        id: '666666',
        date: 'Сегодня, 16:20 i-GMT+3',
        name: 'Death Start Starship Main бургер',
        ingredients: [
            {
                "_id": "60d3b41abdacab0026a733c6",
                "name": "Краторная булка N-200i",
                "type": "bun",
                "proteins": 80,
                "fat": 24,
                "carbohydrates": 53,
                "calories": 420,
                "price": 1255,
                "image": "https://code.s3.yandex.net/react/code/bun-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
                "__v": 0,
                "uuid": "4360d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c8",
                "name": "Филе Люминесцентного тетраодонтимформа",
                "type": "main",
                "proteins": 44,
                "fat": 26,
                "carbohydrates": 85,
                "calories": 643,
                "price": 988,
                "image": "https://code.s3.yandex.net/react/code/meat-03.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-03-large.png",
                "__v": 0,
                "uuid": "4460d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "4560d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "4660d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "4760d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "4860d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "4960d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "5060d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c6",
                "name": "Краторная булка N-200i",
                "type": "bun",
                "proteins": 80,
                "fat": 24,
                "carbohydrates": 53,
                "calories": 420,
                "price": 1255,
                "image": "https://code.s3.yandex.net/react/code/bun-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
                "__v": 0,
                "uuid": "5160d3b41abdacab0026a733c6",
            }
        ],
        price: '777',
    },
    {
        id: '777777',
        date: 'Сегодня, 16:20 i-GMT+3',
        name: 'Death Start Starship Main бургер',
        ingredients: [
            {
                "_id": "60d3b41abdacab0026a733c6",
                "name": "Краторная булка N-200i",
                "type": "bun",
                "proteins": 80,
                "fat": 24,
                "carbohydrates": 53,
                "calories": 420,
                "price": 1255,
                "image": "https://code.s3.yandex.net/react/code/bun-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
                "__v": 0,
                "uuid": "5260d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c8",
                "name": "Филе Люминесцентного тетраодонтимформа",
                "type": "main",
                "proteins": 44,
                "fat": 26,
                "carbohydrates": 85,
                "calories": 643,
                "price": 988,
                "image": "https://code.s3.yandex.net/react/code/meat-03.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-03-large.png",
                "__v": 0,
                "uuid": "5360d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "5460d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "5560d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "5660d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "5760d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "5860d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c9",
                "name": "Мясо бессмертных моллюсков Protostomia",
                "type": "main",
                "proteins": 433,
                "fat": 244,
                "carbohydrates": 33,
                "calories": 420,
                "price": 1337,
                "image": "https://code.s3.yandex.net/react/code/meat-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
                "__v": 0,
                "uuid": "5960d3b41abdacab0026a733c6",
            },
            {
                "_id": "60d3b41abdacab0026a733c6",
                "name": "Краторная булка N-200i",
                "type": "bun",
                "proteins": 80,
                "fat": 24,
                "carbohydrates": 53,
                "calories": 420,
                "price": 1255,
                "image": "https://code.s3.yandex.net/react/code/bun-02.png",
                "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
                "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
                "__v": 0,
                "uuid": "6060d3b41abdacab0026a733c6",
            }
        ],
        price: '666',
    }
]

export const dataOrdersNumbers = {
    ready: ['034533', '034532', '034530', '034527', '034525'],
    inWork: ['034533', '034532', '034530'],
    totalOrders: '28752',
    todayOrders: '138'
}
